### ISSUE TITLE
Love the workshop, issues when dask scheduler is started from command line.

### ISSUE THREAD

**Issue by mlgill** [mrocklin/dask-workshop#1]
Went through the workshop this afternoon and thought it was great. Very Spark-like, but obviously more general.

I ran into some issues with the second notebook when the dask distributed scheduler was started  manually from the command line. The computation complains that the data files are not there for some reason. All works fine when the scheduler is started within the notebook, however. I've inserted some notes [here](https://github.com/mlgill/dask-workshop/blob/master/02-schedulers.ipynb).

Minor comments--there are a couple imports missing from the notebooks. These are noted as above with a bold markdown comment.

Happy to discuss further and help troubleshoot.

**Comment by mrocklin** [comment]
I think I've fixed this in https://github.com/mrocklin/dask-workshop/commit/05ec43dfe799b0b5047892594e5b10ec010bccf0 .  If you have the time to take a look I'd welcome additional feedback.

**Comment by mlgill** [comment]
Thanks! I'll make a note to test tomorrow!
